//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeavinsSoftware.Collection.Program.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InterfaceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterfaceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeavinsSoftware.Collection.Program.Resources.InterfaceResources", typeof(InterfaceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comic Series.
        /// </summary>
        public static string Add_ComicBooks {
            get {
                return ResourceManager.GetString("Add_ComicBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string Add_Product {
            get {
                return ResourceManager.GetString("Add_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        public static string Add_VideoGame {
            get {
                return ResourceManager.GetString("Add_VideoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Publisher.
        /// </summary>
        public static string AddSubCategory_ComicBook {
            get {
                return ResourceManager.GetString("AddSubCategory_ComicBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddSubCategory_Product {
            get {
                return ResourceManager.GetString("AddSubCategory_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add System.
        /// </summary>
        public static string AddSubCategory_VideoGame {
            get {
                return ResourceManager.GetString("AddSubCategory_VideoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string Common_AddCategory {
            get {
                return ResourceManager.GetString("Common_AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Books.
        /// </summary>
        public static string Common_ComicBooks {
            get {
                return ResourceManager.GetString("Common_ComicBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_EditSelected {
            get {
                return ResourceManager.GetString("Common_EditSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Common_ExportData {
            get {
                return ResourceManager.GetString("Common_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string Common_ImportData {
            get {
                return ResourceManager.GetString("Common_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Common_NextPage {
            get {
                return ResourceManager.GetString("Common_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Common_PreviousPage {
            get {
                return ResourceManager.GetString("Common_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Common_Products {
            get {
                return ResourceManager.GetString("Common_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Games.
        /// </summary>
        public static string Common_VideoGames {
            get {
                return ResourceManager.GetString("Common_VideoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string Common_ViewAll {
            get {
                return ResourceManager.GetString("Common_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leavins Software.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export was successful..
        /// </summary>
        public static string Export_SuccessMessage {
            get {
                return ResourceManager.GetString("Export_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Fields_Category {
            get {
                return ResourceManager.GetString("Fields_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Fields_CategoryType {
            get {
                return ResourceManager.GetString("Fields_CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for program updates.
        /// </summary>
        public static string Fields_CheckForProgramUpdates {
            get {
                return ResourceManager.GetString("Fields_CheckForProgramUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Fields_ComicEntryNumber {
            get {
                return ResourceManager.GetString("Fields_ComicEntryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Title.
        /// </summary>
        public static string Fields_ComicEntryTitle {
            get {
                return ResourceManager.GetString("Fields_ComicEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Fields_ComicEntryType {
            get {
                return ResourceManager.GetString("Fields_ComicEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Fields_Condition {
            get {
                return ResourceManager.GetString("Fields_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Fields_ContentProvider {
            get {
                return ResourceManager.GetString("Fields_ContentProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string Fields_Cover {
            get {
                return ResourceManager.GetString("Fields_Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string Fields_DistributionType {
            get {
                return ResourceManager.GetString("Fields_DistributionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Entries.
        /// </summary>
        public static string Fields_EntriesCount {
            get {
                return ResourceManager.GetString("Fields_EntriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Fields_ListType {
            get {
                return ResourceManager.GetString("Fields_ListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Fields_Name {
            get {
                return ResourceManager.GetString("Fields_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Fields_Notes {
            get {
                return ResourceManager.GetString("Fields_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Fields_ProxyServerAddress {
            get {
                return ResourceManager.GetString("Fields_ProxyServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string Fields_ProxyServerPort {
            get {
                return ResourceManager.GetString("Fields_ProxyServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Fields_Publisher {
            get {
                return ResourceManager.GetString("Fields_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty..
        /// </summary>
        public static string Fields_Quantity {
            get {
                return ResourceManager.GetString("Fields_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Fields_System {
            get {
                return ResourceManager.GetString("Fields_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Fields_Title {
            get {
                return ResourceManager.GetString("Fields_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy Server.
        /// </summary>
        public static string Fields_UseProxyServer {
            get {
                return ResourceManager.GetString("Fields_UseProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Program Options.
        /// </summary>
        public static string Home_ProgramOptions {
            get {
                return ResourceManager.GetString("Home_ProgramOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge data from import file.
        /// </summary>
        public static string Import_MergeData {
            get {
                return ResourceManager.GetString("Import_MergeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import was successful..
        /// </summary>
        public static string Import_SuccessMessage {
            get {
                return ResourceManager.GetString("Import_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least one issue (or volume)..
        /// </summary>
        public static string ItemComicPage_NoEntriesError {
            get {
                return ResourceManager.GetString("ItemComicPage_NoEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Options_Finish {
            get {
                return ResourceManager.GetString("Options_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        public static string Options_ProxyExpanderText {
            get {
                return ResourceManager.GetString("Options_ProxyExpanderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Names.
        /// </summary>
        public static string OptionsCategoryNames_Save {
            get {
                return ResourceManager.GetString("OptionsCategoryNames_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Primary Category.
        /// </summary>
        public static string PageTitles_AddMainCategory {
            get {
                return ResourceManager.GetString("PageTitles_AddMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Books - All.
        /// </summary>
        public static string PageTitles_CollectionComic {
            get {
                return ResourceManager.GetString("PageTitles_CollectionComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string PageTitles_CollectionFormat {
            get {
                return ResourceManager.GetString("PageTitles_CollectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products - All.
        /// </summary>
        public static string PageTitles_CollectionProduct {
            get {
                return ResourceManager.GetString("PageTitles_CollectionProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Games - All.
        /// </summary>
        public static string PageTitles_CollectionVideoGame {
            get {
                return ResourceManager.GetString("PageTitles_CollectionVideoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string PageTitles_Export {
            get {
                return ResourceManager.GetString("PageTitles_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string PageTitles_Home {
            get {
                return ResourceManager.GetString("PageTitles_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string PageTitles_Import {
            get {
                return ResourceManager.GetString("PageTitles_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Comic.
        /// </summary>
        public static string PageTitles_ItemExistingComic {
            get {
                return ResourceManager.GetString("PageTitles_ItemExistingComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        public static string PageTitles_ItemExistingProduct {
            get {
                return ResourceManager.GetString("PageTitles_ItemExistingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Game.
        /// </summary>
        public static string PageTitles_ItemExistingVideoGame {
            get {
                return ResourceManager.GetString("PageTitles_ItemExistingVideoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comic Series.
        /// </summary>
        public static string PageTitles_ItemNewComic {
            get {
                return ResourceManager.GetString("PageTitles_ItemNewComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string PageTitles_ItemNewProduct {
            get {
                return ResourceManager.GetString("PageTitles_ItemNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        public static string PageTitles_ItemNewVideoGame {
            get {
                return ResourceManager.GetString("PageTitles_ItemNewVideoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string PageTitles_Options {
            get {
                return ResourceManager.GetString("PageTitles_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Category Names.
        /// </summary>
        public static string PageTitles_OptionsCategoryNames {
            get {
                return ResourceManager.GetString("PageTitles_OptionsCategoryNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIB Collection Manager.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to check online for program updates?.
        /// </summary>
        public static string Startup_CheckUpdatesPrompt {
            get {
                return ResourceManager.GetString("Startup_CheckUpdatesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to CIB Collection Manager is available..
        /// </summary>
        public static string Startup_UpdateAvailable {
            get {
                return ResourceManager.GetString("Startup_UpdateAvailable", resourceCulture);
            }
        }
    }
}
